name: dart_learning
description: A project to learn Dart and Flutter
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  async: ^2.10.0
  meta: ^1.9.1
  synchronized: ^3.1.0

dev_dependencies:
  lints: ^2.1.0