name: dart_learning
description: A project to learn Dart and Flutter
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  synchronized: ^3.0.0

dev_dependencies:
  lints: ^2.1.0