#!/usr/bin/env dart

/// Release management script for FinWise
/// Handles version bumping, changelog generation, and release preparation

import 'dart:io';
import 'dart:convert';

class ReleaseManager {
  static const String changelogFile = 'CHANGELOG.md';
  static const String pubspecFile = 'pubspec.yaml';
  static const String versionFile = 'lib/core/config/version.dart';

  static Future<void> main(List<String> args) async {
    print('🚀 FinWise Release Manager');
    print('=' * 40);

    if (args.isEmpty) {
      _printUsage();
      exit(1);
    }

    final command = args[0];
    final type = args.length > 1 ? args[1] : null;

    try {
      switch (command) {
        case 'bump':
          if (type == null) {
            throw Exception('Version bump type required');
          }
          await _bumpVersion(type);
          break;
        case 'changelog':
          await _generateChangelog();
          break;
        case 'prepare':
          await _prepareRelease();
          break;
        case 'tag':
          await _createGitTag();
          break;
        case 'status':
          await _showReleaseStatus();
          break;
        default:
          throw Exception('Unknown command: $command');
      }

      print('\n✅ Release operation completed successfully!');
    } catch (e) {
      print('\n❌ Release operation failed: $e');
      exit(1);
    }
  }

  static void _printUsage() {
    print('''
Usage: dart tool/release.dart <command> [type]

Commands:
  bump <type>     Bump version (major, minor, patch)
  changelog       Generate changelog from git commits
  prepare         Prepare release (bump version + changelog)
  tag            Create git tag for current version
  status         Show current release status

Examples:
  dart tool/release.dart bump patch
  dart tool/release.dart bump minor
  dart tool/release.dart changelog
  dart tool/release.dart prepare
  dart tool/release.dart tag
  dart tool/release.dart status
    ''');
  }

  static Future<void> _bumpVersion(String type) async {
    print('📈 Bumping version ($type)...');

    final currentVersion = await _getCurrentVersion();
    final newVersion = _calculateNewVersion(currentVersion, type);
    final newBuildNumber = await _getNextBuildNumber();

    print('Current version: $currentVersion');
    print('New version: $newVersion+$newBuildNumber');

    // Update pubspec.yaml
    await _updatePubspecVersion('$newVersion+$newBuildNumber');

    // Update version.dart file
    await _updateVersionFile(newVersion, newBuildNumber);

    print('✅ Version bumped to $newVersion+$newBuildNumber');
  }

  static Future<String> _getCurrentVersion() async {
    final pubspecContent = await File(pubspecFile).readAsString();
    final versionRegex = RegExp(r'version:\s*(\d+\.\d+\.\d+)');
    final match = versionRegex.firstMatch(pubspecContent);

    if (match == null) {
      throw Exception('Could not find version in $pubspecFile');
    }

    return match.group(1)!;
  }

  static Future<int> _getNextBuildNumber() async {
    final pubspecContent = await File(pubspecFile).readAsString();
    final buildRegex = RegExp(r'version:\s*\d+\.\d+\.\d+\+(\d+)');
    final match = buildRegex.firstMatch(pubspecContent);

    if (match != null) {
      return int.parse(match.group(1)!) + 1;
    }

    return 1;
  }

  static String _calculateNewVersion(String currentVersion, String type) {
    final parts = currentVersion.split('.').map(int.parse).toList();

    switch (type) {
      case 'major':
        return '${parts[0] + 1}.0.0';
      case 'minor':
        return '${parts[0]}.${parts[1] + 1}.0';
      case 'patch':
        return '${parts[0]}.${parts[1]}.${parts[2] + 1}';
      default:
        throw Exception('Invalid version bump type: $type');
    }
  }

  static Future<void> _updatePubspecVersion(String newVersion) async {
    final content = await File(pubspecFile).readAsString();
    final updatedContent = content.replaceFirst(
      RegExp(r'version:\s*[\d\.\+]+'),
      'version: $newVersion',
    );

    await File(pubspecFile).writeAsString(updatedContent);
  }

  static Future<void> _updateVersionFile(String version, int buildNumber) async {
    final versionContent = '''
/// FinWise App Version Information
/// Auto-generated by release script - do not edit manually

class AppVersion {
  static const String version = '$version';
  static const int buildNumber = $buildNumber;
  static const String fullVersion = '$version+$buildNumber';

  static String get displayVersion => '$version ($buildNumber)';

  static Map<String, dynamic> toJson() => {
    'version': version,
    'buildNumber': buildNumber,
    'fullVersion': fullVersion,
  };
}
''';

    await File(versionFile).writeAsString(versionContent);
  }

  static Future<void> _generateChangelog() async {
    print('📝 Generating changelog...');

    // Get git log since last tag
    final result = await Process.run('git', [
      'log',
      '--oneline',
      '--pretty=format:%s',
      '--since="1 month ago"'
    ]);

    if (result.exitCode != 0) {
      throw Exception('Failed to get git log');
    }

    final commits = result.stdout.toString().split('\n').where((line) => line.isNotEmpty);

    // Categorize commits
    final features = <String>[];
    final fixes = <String>[];
    final chores = <String>[];
    final others = <String>[];

    for (final commit in commits) {
      final lowerCommit = commit.toLowerCase();
      if (lowerCommit.contains('feat:') || lowerCommit.contains('feature:')) {
        features.add(commit);
      } else if (lowerCommit.contains('fix:') || lowerCommit.contains('bug:')) {
        fixes.add(commit);
      } else if (lowerCommit.contains('chore:') || lowerCommit.contains('refactor:')) {
        chores.add(commit);
      } else {
        others.add(commit);
      }
    }

    // Generate changelog content
    final version = await _getCurrentVersion();
    final now = DateTime.now();
    final dateStr = '${now.year}-${now.month.toString().padLeft(2, '0')}-${now.day.toString().padLeft(2, '0')}';

    final changelog = StringBuffer();
    changelog.writeln('# Changelog');
    changelog.writeln('');
    changelog.writeln('## [$version] - $dateStr');
    changelog.writeln('');

    if (features.isNotEmpty) {
      changelog.writeln('### 🚀 Features');
      for (final feature in features.take(10)) {
        changelog.writeln('- $feature');
      }
      changelog.writeln('');
    }

    if (fixes.isNotEmpty) {
      changelog.writeln('### 🐛 Bug Fixes');
      for (final fix in fixes.take(10)) {
        changelog.writeln('- $fix');
      }
      changelog.writeln('');
    }

    if (chores.isNotEmpty) {
      changelog.writeln('### 🔧 Maintenance');
      for (final chore in chores.take(5)) {
        changelog.writeln('- $chore');
      }
      changelog.writeln('');
    }

    if (others.isNotEmpty) {
      changelog.writeln('### 📝 Other Changes');
      for (final other in others.take(5)) {
        changelog.writeln('- $other');
      }
      changelog.writeln('');
    }

    // Read existing changelog and prepend new content
    String existingContent = '';
    if (await File(changelogFile).exists()) {
      existingContent = await File(changelogFile).readAsString();
    }

    final fullContent = changelog.toString() + existingContent;
    await File(changelogFile).writeAsString(fullContent);

    print('✅ Changelog generated with ${commits.length} commits');
  }

  static Future<void> _prepareRelease() async {
    print('🎯 Preparing release...');

    // Bump patch version
    await _bumpVersion('patch');

    // Generate changelog
    await _generateChangelog();

    // Show release status
    await _showReleaseStatus();

    print('✅ Release prepared successfully');
  }

  static Future<void> _createGitTag() async {
    print('🏷️  Creating git tag...');

    final version = await _getCurrentVersion();
    final buildNumber = await _getNextBuildNumber() - 1; // Already bumped
    final tagName = 'v$version+$buildNumber';

    // Create annotated tag
    final result = await Process.run('git', [
      'tag',
      '-a',
      tagName,
      '-m',
      'Release $tagName\n\n$(head -20 CHANGELOG.md | tail -15)'
    ]);

    if (result.exitCode != 0) {
      throw Exception('Failed to create git tag: ${result.stderr}');
    }

    // Push tag
    final pushResult = await Process.run('git', ['push', 'origin', tagName]);
    if (pushResult.exitCode != 0) {
      throw Exception('Failed to push git tag: ${pushResult.stderr}');
    }

    print('✅ Git tag $tagName created and pushed');
  }

  static Future<void> _showReleaseStatus() async {
    print('📊 Release Status');
    print('-' * 20);

    final version = await _getCurrentVersion();
    final buildNumber = await _getNextBuildNumber() - 1;

    print('Current Version: $version+$buildNumber');
    print('Full Version String: $version+$buildNumber');

    // Check git status
    final gitStatus = await Process.run('git', ['status', '--porcelain']);
    if (gitStatus.stdout.toString().isNotEmpty) {
      print('⚠️  Uncommitted changes detected');
    } else {
      print('✅ Working directory clean');
    }

    // Check if changelog exists
    if (await File(changelogFile).exists()) {
      print('✅ Changelog exists');
    } else {
      print('❌ Changelog missing');
    }

    // Check if version file exists
    if (await File(versionFile).exists()) {
      print('✅ Version file exists');
    } else {
      print('❌ Version file missing');
    }

    // Check for existing tags
    final tagResult = await Process.run('git', ['tag', '--list', 'v$version+*']);
    if (tagResult.stdout.toString().isNotEmpty) {
      print('⚠️  Tag already exists for this version');
    } else {
      print('✅ Ready to create new tag');
    }
  }
}