// Mocks generated by Mockito 5.4.5 from annotations
// in finwise/test/domain/usecases/create_expense_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:finwise/core/errors/failure.dart' as _i5;
import 'package:finwise/domain/entities/expense.dart' as _i6;
import 'package:finwise/domain/repositories/expense_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ExpenseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockExpenseRepository extends _i1.Mock implements _i3.ExpenseRepository {
  MockExpenseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Expense>>> getExpenses({
    required String? userId,
    DateTime? startDate,
    DateTime? endDate,
    List<_i6.ExpenseCategory>? categories,
    String? searchQuery,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExpenses,
          [],
          {
            #userId: userId,
            #startDate: startDate,
            #endDate: endDate,
            #categories: categories,
            #searchQuery: searchQuery,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Expense>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Expense>>(
          this,
          Invocation.method(
            #getExpenses,
            [],
            {
              #userId: userId,
              #startDate: startDate,
              #endDate: endDate,
              #categories: categories,
              #searchQuery: searchQuery,
              #limit: limit,
              #offset: offset,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Expense>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Expense>> getExpense(
          String? expenseId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExpense,
          [expenseId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Expense>>.value(
            _FakeEither_0<_i5.Failure, _i6.Expense>(
          this,
          Invocation.method(
            #getExpense,
            [expenseId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Expense>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Expense>> createExpense(
          _i6.Expense? expense) =>
      (super.noSuchMethod(
        Invocation.method(
          #createExpense,
          [expense],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Expense>>.value(
            _FakeEither_0<_i5.Failure, _i6.Expense>(
          this,
          Invocation.method(
            #createExpense,
            [expense],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Expense>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Expense>> updateExpense(
          _i6.Expense? expense) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateExpense,
          [expense],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Expense>>.value(
            _FakeEither_0<_i5.Failure, _i6.Expense>(
          this,
          Invocation.method(
            #updateExpense,
            [expense],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Expense>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> deleteExpense(String? expenseId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteExpense,
          [expenseId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #deleteExpense,
            [expenseId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, _i3.ExpenseStatistics>> getExpenseStatistics({
    required String? userId,
    required DateTime? startDate,
    required DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExpenseStatistics,
          [],
          {
            #userId: userId,
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i3.ExpenseStatistics>>.value(
                _FakeEither_0<_i5.Failure, _i3.ExpenseStatistics>(
          this,
          Invocation.method(
            #getExpenseStatistics,
            [],
            {
              #userId: userId,
              #startDate: startDate,
              #endDate: endDate,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i3.ExpenseStatistics>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<_i6.ExpenseCategory, double>>>
      getExpensesByCategory({
    required String? userId,
    required DateTime? startDate,
    required DateTime? endDate,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getExpensesByCategory,
              [],
              {
                #userId: userId,
                #startDate: startDate,
                #endDate: endDate,
              },
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure,
                        Map<_i6.ExpenseCategory, double>>>.value(
                _FakeEither_0<_i5.Failure, Map<_i6.ExpenseCategory, double>>(
              this,
              Invocation.method(
                #getExpensesByCategory,
                [],
                {
                  #userId: userId,
                  #startDate: startDate,
                  #endDate: endDate,
                },
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.Failure, Map<_i6.ExpenseCategory, double>>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, List<_i3.MonthlyExpense>>> getMonthlyTrends({
    required String? userId,
    int? months = 12,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMonthlyTrends,
          [],
          {
            #userId: userId,
            #months: months,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i3.MonthlyExpense>>>.value(
                _FakeEither_0<_i5.Failure, List<_i3.MonthlyExpense>>(
          this,
          Invocation.method(
            #getMonthlyTrends,
            [],
            {
              #userId: userId,
              #months: months,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i3.MonthlyExpense>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i3.SyncResult>> syncExpenses(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncExpenses,
          [userId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i3.SyncResult>>.value(
            _FakeEither_0<_i5.Failure, _i3.SyncResult>(
          this,
          Invocation.method(
            #syncExpenses,
            [userId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i3.SyncResult>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Expense>>> searchExpenses({
    required String? userId,
    required String? query,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchExpenses,
          [],
          {
            #userId: userId,
            #query: query,
            #limit: limit,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Expense>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Expense>>(
          this,
          Invocation.method(
            #searchExpenses,
            [],
            {
              #userId: userId,
              #query: query,
              #limit: limit,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Expense>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Expense>>> getRecurringExpenses(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecurringExpenses,
          [userId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Expense>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Expense>>(
          this,
          Invocation.method(
            #getRecurringExpenses,
            [userId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Expense>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Expense>>> bulkCreateExpenses(
          List<_i6.Expense>? expenses) =>
      (super.noSuchMethod(
        Invocation.method(
          #bulkCreateExpenses,
          [expenses],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Expense>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Expense>>(
          this,
          Invocation.method(
            #bulkCreateExpenses,
            [expenses],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Expense>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Expense>>>
      getExpensesNearLocation({
    required String? userId,
    required double? latitude,
    required double? longitude,
    double? radiusKm = 5.0,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getExpensesNearLocation,
              [],
              {
                #userId: userId,
                #latitude: latitude,
                #longitude: longitude,
                #radiusKm: radiusKm,
              },
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Expense>>>.value(
                    _FakeEither_0<_i5.Failure, List<_i6.Expense>>(
              this,
              Invocation.method(
                #getExpensesNearLocation,
                [],
                {
                  #userId: userId,
                  #latitude: latitude,
                  #longitude: longitude,
                  #radiusKm: radiusKm,
                },
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Expense>>>);
}
