// Manual mock implementation for demonstration
// In a real project, this would be generated by Mockito

import 'package:finwise/domain/entities/expense.dart';
import 'package:finwise/domain/repositories/expense_repository.dart';
import 'package:finwise/domain/usecases/create_expense_usecase.dart';
import 'package:mockito/mockito.dart';

// Mock classes for testing
class MockExpenseRepository extends Mock implements ExpenseRepository {
  @override
  Future<Either<Failure, List<Expense>>> getExpenses({
    required String userId,
    DateTime? startDate,
    DateTime? endDate,
    List<ExpenseCategory>? categories,
    String? searchQuery,
    int? limit,
    int? offset,
  }) {
    return super.noSuchMethod(
      Invocation.method(#getExpenses, [], {
        #userId: userId,
        #startDate: startDate,
        #endDate: endDate,
        #categories: categories,
        #searchQuery: searchQuery,
        #limit: limit,
        #offset: offset,
      }),
      returnValue: Future.value(Left(DatabaseFailure('Not implemented'))),
      returnValueForMissingStub: Future.value(Left(DatabaseFailure('Not implemented'))),
    );
  }

  @override
  Future<Either<Failure, Expense>> getExpense(String expenseId) {
    return super.noSuchMethod(
      Invocation.method(#getExpense, [expenseId]),
      returnValue: Future.value(Left(DatabaseFailure('Not implemented'))),
      returnValueForMissingStub: Future.value(Left(DatabaseFailure('Not implemented'))),
    );
  }

  @override
  Future<Either<Failure, Expense>> createExpense(Expense expense) {
    return super.noSuchMethod(
      Invocation.method(#createExpense, [expense]),
      returnValue: Future.value(Left(DatabaseFailure('Not implemented'))),
      returnValueForMissingStub: Future.value(Left(DatabaseFailure('Not implemented'))),
    );
  }

  @override
  Future<Either<Failure, Expense>> updateExpense(Expense expense) {
    return super.noSuchMethod(
      Invocation.method(#updateExpense, [expense]),
      returnValue: Future.value(Left(DatabaseFailure('Not implemented'))),
      returnValueForMissingStub: Future.value(Left(DatabaseFailure('Not implemented'))),
    );
  }

  @override
  Future<Either<Failure, bool>> deleteExpense(String expenseId) {
    return super.noSuchMethod(
      Invocation.method(#deleteExpense, [expenseId]),
      returnValue: Future.value(Left(DatabaseFailure('Not implemented'))),
      returnValueForMissingStub: Future.value(Left(DatabaseFailure('Not implemented'))),
    );
  }

  @override
  Future<Either<Failure, ExpenseStatistics>> getExpenseStatistics({
    required String userId,
    required DateTime startDate,
    required DateTime endDate,
  }) {
    return super.noSuchMethod(
      Invocation.method(#getExpenseStatistics, [], {
        #userId: userId,
        #startDate: startDate,
        #endDate: endDate,
      }),
      returnValue: Future.value(Left(DatabaseFailure('Not implemented'))),
      returnValueForMissingStub: Future.value(Left(DatabaseFailure('Not implemented'))),
    );
  }

  @override
  Future<Either<Failure, Map<ExpenseCategory, double>>> getExpensesByCategory({
    required String userId,
    required DateTime startDate,
    required DateTime endDate,
  }) {
    return super.noSuchMethod(
      Invocation.method(#getExpensesByCategory, [], {
        #userId: userId,
        #startDate: startDate,
        #endDate: endDate,
      }),
      returnValue: Future.value(Left(DatabaseFailure('Not implemented'))),
      returnValueForMissingStub: Future.value(Left(DatabaseFailure('Not implemented'))),
    );
  }

  @override
  Future<Either<Failure, List<MonthlyExpense>>> getMonthlyTrends({
    required String userId,
    int months = 12,
  }) {
    return super.noSuchMethod(
      Invocation.method(#getMonthlyTrends, [], {
        #userId: userId,
        #months: months,
      }),
      returnValue: Future.value(Left(DatabaseFailure('Not implemented'))),
      returnValueForMissingStub: Future.value(Left(DatabaseFailure('Not implemented'))),
    );
  }

  @override
  Future<Either<Failure, SyncResult>> syncExpenses(String userId) {
    return super.noSuchMethod(
      Invocation.method(#syncExpenses, [userId]),
      returnValue: Future.value(Left(DatabaseFailure('Not implemented'))),
      returnValueForMissingStub: Future.value(Left(DatabaseFailure('Not implemented'))),
    );
  }

  @override
  Future<Either<Failure, List<Expense>>> searchExpenses({
    required String userId,
    required String query,
    int? limit,
  }) {
    return super.noSuchMethod(
      Invocation.method(#searchExpenses, [], {
        #userId: userId,
        #query: query,
        #limit: limit,
      }),
      returnValue: Future.value(Left(DatabaseFailure('Not implemented'))),
      returnValueForMissingStub: Future.value(Left(DatabaseFailure('Not implemented'))),
    );
  }

  @override
  Future<Either<Failure, List<Expense>>> getRecurringExpenses(String userId) {
    return super.noSuchMethod(
      Invocation.method(#getRecurringExpenses, [userId]),
      returnValue: Future.value(Left(DatabaseFailure('Not implemented'))),
      returnValueForMissingStub: Future.value(Left(DatabaseFailure('Not implemented'))),
    );
  }

  @override
  Future<Either<Failure, List<Expense>>> bulkCreateExpenses(List<Expense> expenses) {
    return super.noSuchMethod(
      Invocation.method(#bulkCreateExpenses, [expenses]),
      returnValue: Future.value(Left(DatabaseFailure('Not implemented'))),
      returnValueForMissingStub: Future.value(Left(DatabaseFailure('Not implemented'))),
    );
  }

  @override
  Future<Either<Failure, List<Expense>>> getExpensesNearLocation({
    required String userId,
    required double latitude,
    required double longitude,
    double radiusKm = 5.0,
  }) {
    return super.noSuchMethod(
      Invocation.method(#getExpensesNearLocation, [], {
        #userId: userId,
        #latitude: latitude,
        #longitude: longitude,
        #radiusKm: radiusKm,
      }),
      returnValue: Future.value(Left(DatabaseFailure('Not implemented'))),
      returnValueForMissingStub: Future.value(Left(DatabaseFailure('Not implemented'))),
    );
  }
}
